#!/bin/bash
#$ -l h_vmem=11G
#$ -pe smp 32
#$ -l gpu=4
#$ -l h_rt=1:0:0
#$ -cwd
#$ -j y
#$ -m beas
#$ -l cluster=andrena  # Ensure that the job runs on Andrena nodes

#echo $SGE_HGR_gpu

export CUDA_VISIBLE_DEVICES=${SGE_HGR_gpu// /,}
#echo $CUDA_VISIBLE_DEVICES
module load anaconda3/2020.02
module load cudnn/8.1.1-cuda11.2
#nvidia-smi
conda activate lasaftv2-mdx

# Replace the following line with a program or command
python train.py

# Generated by Job Script Builder on 2020-09-20
# For assistance, please email its-research-support@qmul.ac.uk